services:
   nginx:
       container_name: project_nginx
       image:
           nginx:latest
       volumes:
           -    ./:/var/www/
           -   ./devops/nginx/conf.d/:/etc/nginx/conf.d/
       ports:
           -   "8081:80"
       depends_on:
           -   app

   app:
       container_name: project_app
       build:
           context: .
           dockerfile: devops/app/Dockerfile
       volumes:
           -    ./:/var/www
       ports:
           -   "9000:9000"
       depends_on:
           -   db

   db:
       image: mysql:9.0
       restart: always
       volumes:
           - ./tmp/db:/var/lib/mysql
       environment:
           MYSQL_DATABASE: db_shop
           MYSQL_ROOT_PASSWORD: root
       ports:
           -   "3307:3306"
       container_name: project_db
