<?php

namespace App\Http\Requests\API;

use Illuminate\Foundation\Http\FormRequest;

class FilterRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'categories' => 'nullable|array',
            'tags' => 'nullable|array',
            'breweries' => 'nullable|array',
            'prices' => 'nullable|array',
        ];
    }

    public function messages()
    {
        return [
            'title.required' => 'Поле наименование товара должно быть заполнено'
        ]; // TODO: Change the autogenerated stub
    }
}
